(function () {
  "use strict";
  window.ReportReady.then(function () {
    const ui = window.ReportUI, data = ui.data, graph = window.ReportGraphModel, model = graph.build(data);
    const canvas = document.getElementById("relationship-canvas"), context = canvas.getContext("2d"), inspector = document.getElementById("graph-inspector"), status = document.getElementById("graph-status"), empty = document.getElementById("graph-empty"), readableToggle = document.getElementById("filter-readable"), queryToggle = document.getElementById("filter-query"), frameworkToggle = document.getElementById("filter-framework"), queryKind = document.getElementById("filter-query-kind"), search = document.getElementById("graph-search");
    const palette = { readable: "#4f7cff", query: "#ef8f3c", regular: "#91a0b8", framework: "#8a63d2" };
    let view = { scale: 1, x: 0, y: 0 }, dragging = false, lastX = 0, lastY = 0, startX = 0, startY = 0;
    const filters = function () { return { readable: readableToggle.checked, query: queryToggle.checked, framework: frameworkToggle.checked, queryKind: queryKind.value }; };
    const dimensions = function () { const ratio = window.devicePixelRatio || 1; return { ratio: ratio, width: canvas.width / ratio, height: canvas.height / ratio }; };
    const drawArrow = function (from, to, colour, dashed) { context.beginPath(); context.setLineDash(dashed ? [5, 5] : []); context.moveTo(from.x, from.y); context.lineTo(to.x, to.y); context.strokeStyle = colour; context.globalAlpha = 0.55; context.stroke(); context.globalAlpha = 1; context.setLineDash([]); };
    const draw = function () { const size = dimensions(), visible = graph.selectVisible(model, filters(), view, size.width, size.height); context.clearRect(0, 0, size.width, size.height); visible.edges.forEach(function (edge) { drawArrow(graph.screen(model.byKey[edge.from], view), graph.screen(model.byKey[edge.to], view), palette[edge.type], edge.type === "framework"); }); visible.nodes.forEach(function (node) { const point = graph.screen(node, view); context.beginPath(); context.arc(point.x, point.y, node.type === "query" ? 5 : 6, 0, Math.PI * 2); context.fillStyle = palette[node.type]; context.fill(); if (view.scale >= 0.7) { context.font = "11px ui-monospace"; context.fillStyle = "#3b4658"; context.fillText(node.label.length > 28 ? node.label.slice(0, 27) + "…" : node.label, point.x + 9, point.y + 4); } }); empty.hidden = visible.nodes.length > 0; status.textContent = "현재 viewport: node " + ui.format(visible.nodes.length) + " · connection " + ui.format(visible.edges.length) + " · 전체 node " + ui.format(model.nodes.length) + " · 전체 connection " + ui.format(model.edges.length) + " · viewport culling 적용"; };
    const resize = function () { const ratio = window.devicePixelRatio || 1, rectangle = canvas.getBoundingClientRect(); canvas.width = Math.max(1, Math.floor(rectangle.width * ratio)); canvas.height = Math.max(1, Math.floor(rectangle.height * ratio)); context.setTransform(ratio, 0, 0, ratio, 0, 0); draw(); };
    const fit = function () { const size = dimensions(); view = graph.fit(model, filters(), size.width, size.height); draw(); };
    const focusNode = function (node) { const size = dimensions(); view = graph.center(node, view, size.width, size.height); inspector.textContent = JSON.stringify({ type: node.type, data: node.value }, null, 2); draw(); };
    Array.from(new Set(data.query_nodes.map(function (query) { return query.kind; }))).sort().forEach(function (kind) { const option = ui.make("option", kind); option.value = kind; queryKind.appendChild(option); });
    document.getElementById("graph-find").addEventListener("click", function () { const match = graph.find(model, search.value, filters()); if (match) focusNode(match); else inspector.textContent = "일치하는 표시 가능 node가 없습니다."; });
    document.getElementById("graph-fit").addEventListener("click", fit); [readableToggle, queryToggle, frameworkToggle, queryKind].forEach(function (control) { control.addEventListener("change", fit); });
    canvas.addEventListener("wheel", function (event) { event.preventDefault(); const rectangle = canvas.getBoundingClientRect(); view = graph.zoomAt(view, event.deltaY < 0 ? 1.12 : 0.89, { x: event.clientX - rectangle.left, y: event.clientY - rectangle.top }); draw(); }, { passive: false });
    canvas.addEventListener("pointerdown", function (event) { dragging = true; lastX = event.clientX; lastY = event.clientY; startX = event.clientX; startY = event.clientY; canvas.setPointerCapture(event.pointerId); });
    canvas.addEventListener("pointermove", function (event) { if (!dragging) return; view = graph.pan(view, event.clientX - lastX, event.clientY - lastY); lastX = event.clientX; lastY = event.clientY; draw(); });
    canvas.addEventListener("pointerup", function (event) { if (!dragging) return; dragging = false; if (Math.abs(event.clientX - startX) + Math.abs(event.clientY - startY) > 2) return; const rectangle = canvas.getBoundingClientRect(), result = graph.inspectAt(model, filters(), view, { x: event.clientX - rectangle.left, y: event.clientY - rectangle.top }); if (result) inspector.textContent = JSON.stringify(result, null, 2); });
    window.addEventListener("resize", resize); resize(); fit();
  });
}());
